# Generated by Django 4.1.7 on 2023-04-07 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('nom', models.CharField(default='null', max_length=30)),
                ('prenom', models.CharField(default='null', max_length=30)),
                ('email', models.EmailField(default='null', max_length=100, unique=True)),
                ('MotherPwd', models.TextField(default='null')),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 15, 52, 47, 840386, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='null', max_length=100)),
                ('email', models.EmailField(default='null', max_length=100)),
                ('password', models.CharField(default='null', max_length=100)),
                ('dateCreation', models.DateField(auto_now=True)),
                ('users', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='api.users')),
            ],
        ),
    ]
