# Generated by Django 4.1.7 on 2023-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='description',
        ),
        migrations.RemoveField(
            model_name='password',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='password',
            name='siteOrigine',
        ),
        migrations.AddField(
            model_name='password',
            name='email',
            field=models.EmailField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='password',
            name='password',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='password',
            name='website',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='password',
            name='dateCreation',
            field=models.DateField(auto_now=True),
        ),
    ]
