# Generated by Django 4.1.2 on 2022-11-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_tamere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tamere',
        ),
    ]
