# Generated by Django 4.1.7 on 2023-04-07 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_date_joined_alter_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 16, 3, 27, 977515, tzinfo=datetime.timezone.utc)),
        ),
    ]
