# Generated by Django 4.1.7 on 2023-04-07 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_users_last_login_alter_users_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 16, 11, 25, 690573, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 16, 11, 25, 690585, tzinfo=datetime.timezone.utc)),
        ),
    ]
