# Generated by Django 4.1.3 on 2022-11-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_users_tamere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='users',
            name='codePostal',
        ),
        migrations.RemoveField(
            model_name='users',
            name='dateNaissance',
        ),
        migrations.RemoveField(
            model_name='users',
            name='numAdresse',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='users',
            name='telephone',
        ),
    ]
