# Generated by Django 4.1.7 on 2023-03-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_password_description_remove_password_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='api.users'),
        ),
    ]
