# Generated by Django 4.1.7 on 2023-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_password_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='website',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
