# Generated by Django 4.1.7 on 2023-04-10 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_password_email_alter_password_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='api.users'),
        ),
        migrations.AlterField(
            model_name='password',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
