# Generated by Django 4.1.7 on 2023-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_password_website_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='website_uuid',
            field=models.UUIDField(),
        ),
    ]
