# Generated by Django 4.1.4 on 2022-12-10 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_users_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0b25f87-06cc-49b2-a5ba-2606534bba39')),
        ),
    ]
