version: '3'

services:
  frontend:
    image: fraisefrontprod
    build:
      context: ..
      dockerfile: DockerfileFront
    volumes:
        - '../frontend/src:/fraise/frontend/src'
    ports:
        - 127.0.0.1:3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true   
        - WATCHPACK_POLLING=true
      
  backend:
    image: fraisebackprod
    depends_on:
        - db
    restart: on-failure:10
    build:
        context: ..
        dockerfile: Dockerfile
    volumes:
        - '../backend:/fraise/backend'
    ports:
        - 127.0.0.1:8000:8000
    command: sh migration.sh
        
  db:
    image: postgres:13
    volumes:
        - ../backend/postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=fraise
        - POSTGRES_USER=fraise
        - POSTGRES_PASSWORD=fraise
    ports:
        - 127.0.0.1:5432:5432
        
volumes:
    postgres_data: