version: '3'

services:
  frontend:
    image: fraisefront
    build:
      context: ..
      dockerfile: DockerfileFront
    volumes:
        - '../frontend/src:/fraise/frontend/src'
    ports:
        - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true   
        - WATCHPACK_POLLING=true
      
  backend:
    image: fraise
    build:
        context: ..
        dockerfile: Dockerfile
    volumes:
        - '../backend:/fraise/backend'
    ports:
        - 8000:8000
        